/**
 * Curated list of well-known US cities that should always surface at the
 * top of city-autocomplete results (the product's paid traffic is US, and
 * the dataset's population figures are patchy for smaller US towns — a
 * state capital like Montpelier, VT has ~8k people and would otherwise be
 * buried under bigger foreign cities with a similar name).
 *
 * All 50 state capitals + DC + the major metros. Matched against the
 * dataset by normalized city name AND state (province), so "Springfield"
 * boosts specifically Springfield, Illinois — not every Springfield.
 */
export interface MajorUsCity {
  name: string;
  province: string;
}

export const MAJOR_US_CITIES: MajorUsCity[] = [
  // --- All 50 state capitals + DC ---
  { name: "Montgomery", province: "Alabama" },
  { name: "Juneau", province: "Alaska" },
  { name: "Phoenix", province: "Arizona" },
  { name: "Little Rock", province: "Arkansas" },
  { name: "Sacramento", province: "California" },
  { name: "Denver", province: "Colorado" },
  { name: "Hartford", province: "Connecticut" },
  { name: "Dover", province: "Delaware" },
  { name: "Tallahassee", province: "Florida" },
  { name: "Atlanta", province: "Georgia" },
  { name: "Honolulu", province: "Hawaii" },
  { name: "Boise", province: "Idaho" },
  { name: "Springfield", province: "Illinois" },
  { name: "Indianapolis", province: "Indiana" },
  { name: "Des Moines", province: "Iowa" },
  { name: "Topeka", province: "Kansas" },
  { name: "Frankfort", province: "Kentucky" },
  { name: "Baton Rouge", province: "Louisiana" },
  { name: "Augusta", province: "Maine" },
  { name: "Annapolis", province: "Maryland" },
  { name: "Boston", province: "Massachusetts" },
  { name: "Lansing", province: "Michigan" },
  { name: "Saint Paul", province: "Minnesota" },
  { name: "Jackson", province: "Mississippi" },
  { name: "Jefferson City", province: "Missouri" },
  { name: "Helena", province: "Montana" },
  { name: "Lincoln", province: "Nebraska" },
  { name: "Carson City", province: "Nevada" },
  { name: "Concord", province: "New Hampshire" },
  { name: "Trenton", province: "New Jersey" },
  { name: "Santa Fe", province: "New Mexico" },
  { name: "Albany", province: "New York" },
  { name: "Raleigh", province: "North Carolina" },
  { name: "Bismarck", province: "North Dakota" },
  { name: "Columbus", province: "Ohio" },
  { name: "Oklahoma City", province: "Oklahoma" },
  { name: "Salem", province: "Oregon" },
  { name: "Harrisburg", province: "Pennsylvania" },
  { name: "Providence", province: "Rhode Island" },
  { name: "Columbia", province: "South Carolina" },
  { name: "Pierre", province: "South Dakota" },
  { name: "Nashville", province: "Tennessee" },
  { name: "Austin", province: "Texas" },
  { name: "Salt Lake City", province: "Utah" },
  { name: "Montpelier", province: "Vermont" },
  { name: "Richmond", province: "Virginia" },
  { name: "Olympia", province: "Washington" },
  { name: "Charleston", province: "West Virginia" },
  { name: "Madison", province: "Wisconsin" },
  { name: "Cheyenne", province: "Wyoming" },
  { name: "Washington", province: "District of Columbia" },

  // --- Major metros (non-capitals) ---
  { name: "New York", province: "New York" },
  { name: "Los Angeles", province: "California" },
  { name: "Chicago", province: "Illinois" },
  { name: "Houston", province: "Texas" },
  { name: "Philadelphia", province: "Pennsylvania" },
  { name: "San Antonio", province: "Texas" },
  { name: "San Diego", province: "California" },
  { name: "Dallas", province: "Texas" },
  { name: "San Jose", province: "California" },
  { name: "Jacksonville", province: "Florida" },
  { name: "Fort Worth", province: "Texas" },
  { name: "San Francisco", province: "California" },
  { name: "Charlotte", province: "North Carolina" },
  { name: "Seattle", province: "Washington" },
  { name: "Detroit", province: "Michigan" },
  { name: "El Paso", province: "Texas" },
  { name: "Memphis", province: "Tennessee" },
  { name: "Portland", province: "Oregon" },
  { name: "Las Vegas", province: "Nevada" },
  { name: "Louisville", province: "Kentucky" },
  { name: "Baltimore", province: "Maryland" },
  { name: "Milwaukee", province: "Wisconsin" },
  { name: "Albuquerque", province: "New Mexico" },
  { name: "Tucson", province: "Arizona" },
  { name: "Fresno", province: "California" },
  { name: "Mesa", province: "Arizona" },
  { name: "Kansas City", province: "Missouri" },
  { name: "Long Beach", province: "California" },
  { name: "Omaha", province: "Nebraska" },
  { name: "Miami", province: "Florida" },
  { name: "Oakland", province: "California" },
  { name: "Minneapolis", province: "Minnesota" },
  { name: "Tulsa", province: "Oklahoma" },
  { name: "Wichita", province: "Kansas" },
  { name: "New Orleans", province: "Louisiana" },
  { name: "Arlington", province: "Texas" },
  { name: "Cleveland", province: "Ohio" },
  { name: "Tampa", province: "Florida" },
  { name: "Aurora", province: "Colorado" },
  { name: "Anaheim", province: "California" },
  { name: "Santa Ana", province: "California" },
  { name: "Saint Louis", province: "Missouri" },
  { name: "Pittsburgh", province: "Pennsylvania" },
  { name: "Corpus Christi", province: "Texas" },
  { name: "Cincinnati", province: "Ohio" },
  { name: "Anchorage", province: "Alaska" },
  { name: "Henderson", province: "Nevada" },
  { name: "Greensboro", province: "North Carolina" },
  { name: "Plano", province: "Texas" },
  { name: "Newark", province: "New Jersey" },
  { name: "Toledo", province: "Ohio" },
  { name: "Orlando", province: "Florida" },
  { name: "Jersey City", province: "New Jersey" },
  { name: "Chandler", province: "Arizona" },
  { name: "Fort Wayne", province: "Indiana" },
  { name: "Buffalo", province: "New York" },
  { name: "Durham", province: "North Carolina" },
  { name: "Saint Petersburg", province: "Florida" },
  { name: "Irvine", province: "California" },
  { name: "Laredo", province: "Texas" },
  { name: "Lubbock", province: "Texas" },
  { name: "Norfolk", province: "Virginia" },
  { name: "Reno", province: "Nevada" },
  { name: "Winston-Salem", province: "North Carolina" },
  { name: "Glendale", province: "Arizona" },
  { name: "Scottsdale", province: "Arizona" },
  { name: "Irving", province: "Texas" },
  { name: "Chesapeake", province: "Virginia" },
  { name: "Fremont", province: "California" },
  { name: "Spokane", province: "Washington" },
  { name: "Tacoma", province: "Washington" },
  { name: "Rochester", province: "New York" },
  { name: "Grand Rapids", province: "Michigan" },
  { name: "Huntsville", province: "Alabama" },
  { name: "Knoxville", province: "Tennessee" },
  { name: "Fort Lauderdale", province: "Florida" },
  { name: "Savannah", province: "Georgia" },
  { name: "Birmingham", province: "Alabama" },
  { name: "Bridgeport", province: "Connecticut" },
  { name: "Colorado Springs", province: "Colorado" },
  { name: "Virginia Beach", province: "Virginia" },
];
