import { Container } from "@/components/ui/Container";
import { OrbitScatter } from "@/components/ui/OrbitScatter";

export function AstrologerBio() {
  return (
    <section className="relative overflow-hidden py-20">
      <OrbitScatter />
      <Container width="lg" className="relative">
        <div className="mx-auto grid max-w-3xl items-center gap-10 sm:grid-cols-[160px_1fr]">
          <div className="mx-auto flex h-40 w-40 items-center justify-center rounded-full border border-burgundy/30 bg-burgundy/5 font-display text-4xl text-burgundy">
            JG
          </div>
          <div className="text-center sm:text-left">
            <p className="font-mono text-xs uppercase tracking-[0.2em] text-ink-faint">
              Your astrologer
            </p>
            <h2 className="mt-2 font-display text-2xl font-medium text-aubergine sm:text-3xl">
              Julia Grinenko
            </h2>
            <p className="mt-1 text-sm text-ink-muted">
              10+ years of practice
            </p>
            <p className="mx-auto mt-4 max-w-lg text-balance text-base leading-relaxed text-ink-muted sm:mx-0">
              Julia has been reading natal charts professionally for over a
              decade, working with clients across Europe and North America.
              Her approach blends traditional Western astrology with a
              grounded, practical focus — she writes toward what a client
              can actually use, not vague predictions. Every report in this
              service is read and written by Julia personally, not
              generated by software.
            </p>
          </div>
        </div>
      </Container>
    </section>
  );
}
